application: streetcode-sw
version: deployment
runtime: python
api_version: 1
threadsafe: false

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico
  mime_type: image/vnd.microsoft.icon

- url: /images
  static_dir: images

- url: /css
  static_dir: css

- url: /js
  static_dir: js

- url: /rest/css
  static_dir: rest/css

- url: /rest/js
  static_dir: rest/js

- url: .*
  script: main.py

skip_files:
- ^app\.yaml$
- ^index\.yaml$
- ^.*\#$
- ^.*~$
- ^.*\.py[co]$
- ^(.*/)?\.
- ^.*\.bak$
- ^.*\.orig$
- ^.*/TAGS$
- ^js/libs/jquery-mobile/demos
